version: "3.9"
services:
    web:
        restart: always
        build: .
        ports:
            - 3000:3000
        environment:
            # Youtube Config
            YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
            YOUTUBE_API_URL: ${YOUTUBE_API_URL}

            # Mongo Config
            MONGO_PORT: ${MONGO_PORT}
            MONGO_AUTH_DB: ${MONGO_AUTH_DB}
            MONGODB_URL: ${MONGODB_URL}

            # HTTP Config
            HTTP_PORT: ${HTTP_PORT}

            # Logical Config
            DEFAULT_SEARCH_VALUE: ${DEFAULT_SEARCH_VALUE}
            DEFAULT_PAGE_SIZE: ${DEFAULT_PAGE_SIZE}
            CRON_SCHEDULE_TIME: ${CRON_SCHEDULE_TIME}
            MAX_FETCH_RESULTS: ${MAX_FETCH_RESULTS}

        depends_on: 
            - mongo

    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        depends_on:
            - mongo